import os
from anthropic import AsyncAnthropic
import logging

logger = logging.getLogger(__name__)

class LLMClient:
    def __init__(self):
        self.api_key = os.getenv("ANTHROPIC_API_KEY")
        if self.api_key:
            self.client = AsyncAnthropic(api_key=self.api_key)
        else:
            self.client = None

    async def analyze_exception(self, error_type: str, related_sku: str, description: str) -> str:
        """
        Analyzes an exception using the LLM and suggests a resolution.
        """
        if not self.client:
            logger.warning("No ANTHROPIC_API_KEY found. Skipping LLM exception analysis.")
            return "No LLM analysis available. Please check the error description manually."

        system_prompt = (
            "You are an expert ERP and Manufacturing assistant for Produce.Ai.\n"
            "Your job is to read an exception generated by the manufacturing pipeline "
            "and suggest a clear, actionable resolution for the user.\n"
            "Keep the resolution under 3 sentences. Be highly specific to the error type."
        )

        user_prompt = (
            f"Exception Type: {error_type}\n"
            f"Related SKU: {related_sku or 'N/A'}\n"
            f"Description: {description}\n\n"
            "Suggest a resolution plan:"
        )

        try:
            response = await self.client.messages.create(
                model="claude-3-haiku-20240307",
                system=system_prompt,
                messages=[
                    {"role": "user", "content": user_prompt}
                ],
                temperature=0.3,
                max_tokens=150
            )
            return response.content[0].text.strip()
        except Exception as e:
            logger.error(f"LLM API call failed: {e}")
            return "LLM analysis failed due to an API error."
