"""add invoicing models

Revision ID: 265152e654d1
Revises: fd387f0f3546
Create Date: 2026-07-19 21:41:59.673836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '265152e654d1'
down_revision: Union[str, None] = 'fd387f0f3546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stg_sales_invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('hdr_id', sa.Integer(), nullable=True),
    sa.Column('erp_invoice_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'INVOICED', 'PARTIAL', 'FAILED', name='invoicingstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['hdr_id'], ['stg_shopify_sales_order_hdr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stg_sales_invoice_id'), 'stg_sales_invoice', ['id'], unique=False)
    op.create_index(op.f('ix_stg_sales_invoice_run_id'), 'stg_sales_invoice', ['run_id'], unique=False)
    op.add_column('stg_shopify_sales_order_line', sa.Column('invoicing_status', sa.Enum('PENDING', 'INVOICED', 'PARTIAL', 'FAILED', name='invoicingstatus'), nullable=True))
    op.add_column('stg_shopify_sales_order_line', sa.Column('fulfilled_qty', sa.Integer(), nullable=True))
    op.add_column('stg_shopify_sales_order_line', sa.Column('unfulfilled_qty', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stg_shopify_sales_order_line', 'unfulfilled_qty')
    op.drop_column('stg_shopify_sales_order_line', 'fulfilled_qty')
    op.drop_column('stg_shopify_sales_order_line', 'invoicing_status')
    op.drop_index(op.f('ix_stg_sales_invoice_run_id'), table_name='stg_sales_invoice')
    op.drop_index(op.f('ix_stg_sales_invoice_id'), table_name='stg_sales_invoice')
    op.drop_table('stg_sales_invoice')
    # ### end Alembic commands ###
