"""Initial migration

Revision ID: fd387f0f3546
Revises: 
Create Date: 2026-07-13 22:37:42.808576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd387f0f3546'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bom_recipe_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fg_item_code', sa.String(), nullable=True),
    sa.Column('raw_material_code', sa.String(), nullable=True),
    sa.Column('qty', sa.Float(), nullable=True),
    sa.Column('uom', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bom_recipe_master_fg_item_code'), 'bom_recipe_master', ['fg_item_code'], unique=False)
    op.create_index(op.f('ix_bom_recipe_master_id'), 'bom_recipe_master', ['id'], unique=False)
    op.create_table('exception_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('related_sku', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', name='exceptionstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exception_queue_id'), 'exception_queue', ['id'], unique=False)
    op.create_table('map_shopify_sku_erp_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shopify_sku', sa.String(), nullable=True),
    sa.Column('erp_item_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_map_shopify_sku_erp_item_erp_item_code'), 'map_shopify_sku_erp_item', ['erp_item_code'], unique=False)
    op.create_index(op.f('ix_map_shopify_sku_erp_item_id'), 'map_shopify_sku_erp_item', ['id'], unique=False)
    op.create_index(op.f('ix_map_shopify_sku_erp_item_shopify_sku'), 'map_shopify_sku_erp_item', ['shopify_sku'], unique=True)
    op.create_table('shopify_order_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shopify_order_id', sa.String(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopify_order_raw_id'), 'shopify_order_raw', ['id'], unique=False)
    op.create_index(op.f('ix_shopify_order_raw_shopify_order_id'), 'shopify_order_raw', ['shopify_order_id'], unique=True)
    op.create_table('stg_shopify_sales_order_hdr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shopify_order_id', sa.String(), nullable=True),
    sa.Column('customer_email', sa.String(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('financial_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stg_shopify_sales_order_hdr_id'), 'stg_shopify_sales_order_hdr', ['id'], unique=False)
    op.create_index(op.f('ix_stg_shopify_sales_order_hdr_shopify_order_id'), 'stg_shopify_sales_order_hdr', ['shopify_order_id'], unique=True)
    op.create_table('stg_work_order_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planning_date', sa.DateTime(), nullable=True),
    sa.Column('erp_fg_item_code', sa.String(), nullable=True),
    sa.Column('net_qty', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CREATED', 'FAILED', name='workorderstatus'), nullable=True),
    sa.Column('erp_work_order_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stg_work_order_plan_erp_fg_item_code'), 'stg_work_order_plan', ['erp_fg_item_code'], unique=False)
    op.create_index(op.f('ix_stg_work_order_plan_id'), 'stg_work_order_plan', ['id'], unique=False)
    op.create_table('stg_shopify_sales_order_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hdr_id', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('processing_status', sa.Enum('PENDING', 'CLASSIFIED', 'ERROR', name='processingstatus'), nullable=True),
    sa.ForeignKeyConstraint(['hdr_id'], ['stg_shopify_sales_order_hdr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stg_shopify_sales_order_line_id'), 'stg_shopify_sales_order_line', ['id'], unique=False)
    op.create_index(op.f('ix_stg_shopify_sales_order_line_sku'), 'stg_shopify_sales_order_line', ['sku'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stg_shopify_sales_order_line_sku'), table_name='stg_shopify_sales_order_line')
    op.drop_index(op.f('ix_stg_shopify_sales_order_line_id'), table_name='stg_shopify_sales_order_line')
    op.drop_table('stg_shopify_sales_order_line')
    op.drop_index(op.f('ix_stg_work_order_plan_id'), table_name='stg_work_order_plan')
    op.drop_index(op.f('ix_stg_work_order_plan_erp_fg_item_code'), table_name='stg_work_order_plan')
    op.drop_table('stg_work_order_plan')
    op.drop_index(op.f('ix_stg_shopify_sales_order_hdr_shopify_order_id'), table_name='stg_shopify_sales_order_hdr')
    op.drop_index(op.f('ix_stg_shopify_sales_order_hdr_id'), table_name='stg_shopify_sales_order_hdr')
    op.drop_table('stg_shopify_sales_order_hdr')
    op.drop_index(op.f('ix_shopify_order_raw_shopify_order_id'), table_name='shopify_order_raw')
    op.drop_index(op.f('ix_shopify_order_raw_id'), table_name='shopify_order_raw')
    op.drop_table('shopify_order_raw')
    op.drop_index(op.f('ix_map_shopify_sku_erp_item_shopify_sku'), table_name='map_shopify_sku_erp_item')
    op.drop_index(op.f('ix_map_shopify_sku_erp_item_id'), table_name='map_shopify_sku_erp_item')
    op.drop_index(op.f('ix_map_shopify_sku_erp_item_erp_item_code'), table_name='map_shopify_sku_erp_item')
    op.drop_table('map_shopify_sku_erp_item')
    op.drop_index(op.f('ix_exception_queue_id'), table_name='exception_queue')
    op.drop_table('exception_queue')
    op.drop_index(op.f('ix_bom_recipe_master_id'), table_name='bom_recipe_master')
    op.drop_index(op.f('ix_bom_recipe_master_fg_item_code'), table_name='bom_recipe_master')
    op.drop_table('bom_recipe_master')
    # ### end Alembic commands ###
